language: node_js
node_js: 14.17.3

install: 
  npm ci
  
script: echo "npm test temporarily disabled"

deploy: 
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
